### ISSUE TITLE
Create a bower package

### ISSUE THREAD

**Issue by ggrossetie** [asciidocfx/asciidoctor.js-reveal-demo#1]
This is great!
I want to integrate your work into the Chrome Extension but I think that would be better to create a (bower) package to ease integration into other projects.

Also I have some questions about how does this work:
- Where did you get `jade.js` ? https://raw.githubusercontent.com/jadejs/jade/1.11.0/jade.js ?
  - If so maybe we can pre-compile jade template to JavaScript and use the runtime library: https://github.com/jadejs/jade#browser-support ?
- Could you share the Ruby code used to generate `asciidoctor-reveal.js` ?
- Did you made some changes to Asciidoctor core ? or I can just use `asciidoctor-all.js` from the asciidoctor.js repository ?

Thanks

**Comment by rahmanusta** [comment]
Hello @Mogztter ;

Also I have some questions about how does this work:
- Where did you get `jade.js` ? https://raw.githubusercontent.com/jadejs/jade/1.11.0/jade.js ?
  - If so maybe we can pre-compile jade template to JavaScript and use the runtime library: https://github.com/jadejs/jade#browser-support ?

Yes, I used `jade.js` linked above, I didnt precompiled templates for developing stage, we can precompile the templates as you know.
- Could you share the Ruby code used to generate `asciidoctor-reveal.js` ?
- Did you made some changes to Asciidoctor core ? or I can just use `asciidoctor-all.js` from the asciidoctor.js repository ?

I updated the repo https://github.com/asciidocfx/asciidoctor, we can look at https://github.com/asciidocfx/asciidoctor/commit/ff014b82c0ab1772d5ef6c2cd86d2a5dfb59ca14 and https://github.com/asciidocfx/asciidoctor/commit/95d9fb3861543ba250115fbb702a0a0b6de89d68

You can see the latest templates here https://github.com/asciidocfx/asciidoctorjs-slide-templates.git and dist folder here https://github.com/asciidocfx/asciidoctor.js

How can we go next step ? @Mogztter @mojavelinux

**Comment by mojavelinux** [comment]
The next steps are as follows:
1. Get the template converter merged into the asciidoctor.js repository (of course compiled using Opal).
2. Get the jade templates merged into the upstream repository (asciidoctor-deck.js and asciidoctor-reveal.js)
3. Create a Bower or npm package for the jade templates so they can be retrieved using a package manager (I'm also open to continuing to use a submodule if that's easier to start)

We want to make sure we do these steps so we aren't copying files between repositories ad hoc.

**Comment by cmoulliard** [comment]
What is the status of this issue created one year ago ?

**Comment by obilodeau** [comment]
We are definitely getting there with all the work that went into Asciidoctor.js / Jade / Node support in asciidoctor-reveal.js.

Thanks to @Mogztter, @cmoulliard and @mojavelinux!

**Comment by ggrossetie** [comment]
It's now pretty straight forward to use the reveal.js converter in a JavaScript environment, see https://github.com/asciidoctor/asciidoctor-reveal.js#node-javascript-setup
